server:
  port: 3000
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql:///example_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


